#!/bin/bash

set -e

echo ""
echo "🔐 StudyFlow — PART 7 Supabase Accounts"
echo "========================================"
echo ""

BACKUP="backup-part7-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP"

cp server.js "$BACKUP/server.js" 2>/dev/null || true
cp data/users.json "$BACKUP/users.json" 2>/dev/null || true
cp .env "$BACKUP/.env" 2>/dev/null || true

echo "✅ Backup created: $BACKUP"


# =========================================================
# SUPABASE USER TABLE
# =========================================================

cat > supabase-auth-schema.sql <<'SQL'

create table if not exists public.studyflow_users (

  id bigint generated by default as identity primary key,

  email text not null unique,

  password_hash text not null,

  name text not null default '',

  university text not null default '',

  major text not null default '',

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now()

);


create unique index if not exists
studyflow_users_email_lower_idx

on public.studyflow_users (
  lower(email)
);


alter table public.studyflow_users
enable row level security;

SQL


# =========================================================
# AUTH ROUTER
# =========================================================

cat > auth-routes.js <<'EOF'

import express from "express";
import bcrypt from "bcryptjs";

import {
  createClient
} from "@supabase/supabase-js";


const router =
  express.Router();


function getSupabase(){

  const url =
    process.env.SUPABASE_URL;

  const secret =
    process.env.SUPABASE_SECRET_KEY
    ||
    process.env.SUPABASE_SERVICE_ROLE_KEY;


  if(!url || !secret){
    return null;
  }


  return createClient(
    url,
    secret,
    {
      auth:{
        persistSession:false,
        autoRefreshToken:false
      }
    }
  );

}


function cleanEmail(value){

  return String(value || "")
    .trim()
    .toLowerCase();

}


function publicUser(user){

  return {

    id:user.id,

    email:user.email,

    name:user.name || "",

    university:user.university || "",

    major:user.major || ""

  };

}


function requireDatabase(res){

  const supabase =
    getSupabase();


  if(!supabase){

    res.status(503).json({
      error:
        "Supabase account storage is not configured."
    });

    return null;

  }


  return supabase;

}


/* =========================================================
   REGISTER
========================================================= */

router.post(
  "/register",

  async (req,res) => {

    const supabase =
      requireDatabase(res);


    if(!supabase){
      return;
    }


    const email =
      cleanEmail(req.body?.email);


    const password =
      String(
        req.body?.password || ""
      );


    const name =
      String(
        req.body?.name || ""
      ).trim();


    if(!email.includes("@")){

      return res
        .status(400)
        .json({
          error:
            "Enter a valid email address."
        });

    }


    if(password.length < 6){

      return res
        .status(400)
        .json({
          error:
            "Password must be at least 6 characters."
        });

    }


    try{

      const {
        data:existing,
        error:findError
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .select(
          "id"
        )

        .eq(
          "email",
          email
        )

        .maybeSingle();


      if(findError){
        throw findError;
      }


      if(existing){

        return res
          .status(409)
          .json({
            error:
              "An account with this email already exists."
          });

      }


      const password_hash =
        await bcrypt.hash(
          password,
          12
        );


      const {
        data:user,
        error
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .insert({

          email,

          password_hash,

          name:
            name ||
            email.split("@")[0],

          university:"",

          major:""

        })

        .select(
          "id,email,name,university,major"
        )

        .single();


      if(error){
        throw error;
      }


      req.session.userId =
        user.id;


      req.session.save(
        () => {

          res.json({
            user:
              publicUser(user)
          });

        }
      );


    }catch(error){

      console.error(
        "Supabase register:",
        error
      );


      res
        .status(500)
        .json({
          error:
            error.message ||
            "Could not create account."
        });

    }

  }
);


/* =========================================================
   LOGIN
========================================================= */

router.post(
  "/login",

  async (req,res) => {

    const supabase =
      requireDatabase(res);


    if(!supabase){
      return;
    }


    const email =
      cleanEmail(
        req.body?.email
      );


    const password =
      String(
        req.body?.password || ""
      );


    try{

      const {
        data:user,
        error
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .select(
          "id,email,password_hash,name,university,major"
        )

        .eq(
          "email",
          email
        )

        .maybeSingle();


      if(error){
        throw error;
      }


      if(!user){

        return res
          .status(401)
          .json({
            error:
              "Incorrect email or password."
          });

      }


      const valid =
        await bcrypt.compare(
          password,
          user.password_hash
        );


      if(!valid){

        return res
          .status(401)
          .json({
            error:
              "Incorrect email or password."
          });

      }


      req.session.userId =
        user.id;


      req.session.save(
        () => {

          res.json({
            user:
              publicUser(user)
          });

        }
      );


    }catch(error){

      console.error(
        "Supabase login:",
        error
      );


      res
        .status(500)
        .json({
          error:
            error.message ||
            "Login failed."
        });

    }

  }
);


/* =========================================================
   LOGOUT
========================================================= */

router.post(
  "/logout",

  (req,res) => {

    req.session.destroy(
      () => {

        res.json({
          success:true
        });

      }
    );

  }
);


/* =========================================================
   CURRENT USER
========================================================= */

router.get(
  "/me",

  async (req,res) => {

    if(!req.session?.userId){

      return res
        .status(401)
        .json({
          error:
            "Not logged in."
        });

    }


    const supabase =
      requireDatabase(res);


    if(!supabase){
      return;
    }


    try{

      const {
        data:user,
        error
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .select(
          "id,email,name,university,major"
        )

        .eq(
          "id",
          req.session.userId
        )

        .maybeSingle();


      if(error){
        throw error;
      }


      if(!user){

        req.session.destroy(
          () => {}
        );


        return res
          .status(401)
          .json({
            error:
              "Account no longer exists."
          });

      }


      res.json({
        user:
          publicUser(user)
      });


    }catch(error){

      console.error(
        "Supabase /me:",
        error
      );


      res
        .status(500)
        .json({
          error:
            error.message
        });

    }

  }
);


/* =========================================================
   PROFILE
========================================================= */

router.put(
  "/profile",

  async (req,res) => {

    if(!req.session?.userId){

      return res
        .status(401)
        .json({
          error:
            "Login required."
        });

    }


    const supabase =
      requireDatabase(res);


    if(!supabase){
      return;
    }


    const update = {

      updated_at:
        new Date()
        .toISOString()

    };


    if(
      typeof req.body?.name ===
      "string"
    ){

      update.name =
        req.body.name.trim();

    }


    if(
      typeof req.body?.university ===
      "string"
    ){

      update.university =
        req.body.university.trim();

    }


    if(
      typeof req.body?.major ===
      "string"
    ){

      update.major =
        req.body.major.trim();

    }


    try{

      const {
        data:user,
        error
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .update(update)

        .eq(
          "id",
          req.session.userId
        )

        .select(
          "id,email,name,university,major"
        )

        .single();


      if(error){
        throw error;
      }


      res.json({
        user:
          publicUser(user)
      });


    }catch(error){

      console.error(
        "Profile update:",
        error
      );


      res
        .status(500)
        .json({
          error:
            error.message ||
            "Profile update failed."
        });

    }

  }
);


export default router;

EOF


# =========================================================
# OLD USERS MIGRATION
# =========================================================

cat > migrate-users-to-supabase.js <<'EOF'

import fs from "fs";

import dotenv from "dotenv";

import {
  createClient
} from "@supabase/supabase-js";


dotenv.config();


const url =
  process.env.SUPABASE_URL;


const secret =
  process.env.SUPABASE_SECRET_KEY
  ||
  process.env.SUPABASE_SERVICE_ROLE_KEY;


if(!url || !secret){

  console.error(
    "❌ Supabase credentials are missing from .env"
  );

  process.exit(1);

}


const supabase =
  createClient(
    url,
    secret,
    {
      auth:{
        persistSession:false
      }
    }
  );


const file =
  "data/users.json";


if(!fs.existsSync(file)){

  console.log(
    "ℹ️ No old data/users.json found."
  );

  process.exit(0);

}


let users;


try{

  users =
    JSON.parse(
      fs.readFileSync(
        file,
        "utf8"
      )
    );

}catch(error){

  console.error(
    "❌ Could not read users.json:",
    error.message
  );

  process.exit(1);

}


if(!Array.isArray(users)){

  console.error(
    "❌ users.json is not an array."
  );

  process.exit(1);

}


console.log(
  `Found ${users.length} local users.`
);


for(const oldUser of users){

  const email =
    String(
      oldUser.email || ""
    )
    .trim()
    .toLowerCase();


  if(
    !email ||
    !oldUser.passwordHash
  ){

    console.log(
      "Skipping invalid user:",
      email
    );

    continue;

  }


  const row = {

    email,

    password_hash:
      oldUser.passwordHash,

    name:
      oldUser.name || "",

    university:
      oldUser.university || "",

    major:
      oldUser.major || "",

    updated_at:
      new Date()
      .toISOString()

  };


  /*
    Preserve old numeric StudyFlow ID.
    This keeps localStorage/cloud snapshot IDs compatible.
  */

  if(
    oldUser.id !== undefined &&
    oldUser.id !== null
  ){

    row.id =
      Number(oldUser.id);

  }


  const {
    error
  } =
    await supabase

    .from(
      "studyflow_users"
    )

    .upsert(
      row,
      {
        onConflict:
          "email"
      }
    );


  if(error){

    console.error(
      `❌ ${email}:`,
      error.message
    );

  }else{

    console.log(
      `✅ ${email}`
    );

  }

}


console.log("");
console.log(
  "🎉 User migration finished."
);

EOF


# =========================================================
# PATCH SERVER
# =========================================================

python3 <<'PY'

from pathlib import Path


p =
    Path("server.js")


s =
    p.read_text()


# IMPORT AUTH ROUTER

if 'from "./auth-routes.js"' not in s:

    lines =
        s.splitlines()


    last_import =
        0


    for i,line in enumerate(lines):

        if line.startswith("import "):
            last_import = i


    lines.insert(
        last_import + 1,
        'import supabaseAuthRouter from "./auth-routes.js";'
    )


    s =
        "\n".join(lines)


# Mount BEFORE old JSON auth routes.
# cloudRouter is already mounted after express-session,
# so mounting directly before cloudRouter gives us a safe location.

mount = '''

/*
  Supabase-backed account routes.
  These are mounted before the old JSON routes,
  so Register/Login/Profile now use Postgres.
*/

app.use("/api", supabaseAuthRouter);

'''


if 'app.use("/api", supabaseAuthRouter);' not in s:

    marker =
        'app.use("/api/cloud", cloudRouter);'


    if marker in s:

        s =
            s.replace(
                marker,
                mount + "\n" + marker,
                1
            )

    else:

        # fallback: place before first existing auth route

        markers = [
            'app.post("/api/register"',
            "app.post('/api/register'"
        ]


        inserted =
            False


        for marker in markers:

            pos =
                s.find(marker)


            if pos != -1:

                s =
                    s[:pos] + \
                    mount + \
                    "\n" + \
                    s[pos:]


                inserted =
                    True

                break


        if not inserted:

            raise SystemExit(
                "Could not find safe place to mount Supabase auth."
            )


p.write_text(s)


print(
    "✅ server.js now uses Supabase account routes"
)

PY


# =========================================================
# GITIGNORE
# =========================================================

touch .gitignore

grep -qxF "data/users.json" .gitignore \
|| echo "data/users.json" >> .gitignore

grep -qxF ".env" .gitignore \
|| echo ".env" >> .gitignore


# =========================================================
# CHECK
# =========================================================

echo ""
echo "🧪 Checking code..."

node --check auth-routes.js
node --check migrate-users-to-supabase.js
node --check server.js

echo ""
echo "✅ Syntax OK"


# =========================================================
# COPY SQL TO MAC CLIPBOARD
# =========================================================

if command -v pbcopy >/dev/null 2>&1
then

  pbcopy < supabase-auth-schema.sql

  echo ""
  echo "📋 Supabase SQL copied to your clipboard."

fi


echo ""
echo "========================================"
echo "✅ PART 7 CODE INSTALLED"
echo "========================================"
echo ""
echo "NEXT:"
echo ""
echo "1. Supabase → SQL Editor → New query"
echo "2. Press Command+V"
echo "3. Press Run"
echo ""
echo "After SQL succeeds run:"
echo ""
echo "node migrate-users-to-supabase.js"
echo ""
echo "Then:"
echo ""
echo "npm start"
echo ""

