#!/bin/bash

set -e

echo ""
echo "🔐 StudyFlow — PART 8 Production Auth"
echo "====================================="
echo ""

# =========================================================
# BACKUP
# =========================================================

BACKUP="backup-part8-$(date +%Y%m%d-%H%M%S)"

mkdir -p "$BACKUP"

cp server.js "$BACKUP/server.js" 2>/dev/null || true
cp auth-routes.js "$BACKUP/auth-routes.js" 2>/dev/null || true
cp package.json "$BACKUP/package.json" 2>/dev/null || true
cp .env "$BACKUP/.env" 2>/dev/null || true
cp -R public "$BACKUP/public" 2>/dev/null || true

echo "✅ Backup created: $BACKUP"


# =========================================================
# INSTALL PACKAGES
# =========================================================

echo "📦 Installing production auth packages..."

npm install pg connect-pg-simple resend


# =========================================================
# SUPABASE SQL
# =========================================================

cat > supabase-production-auth.sql <<'SQL'

-- ========================================================
-- StudyFlow Production Authentication
-- ========================================================

alter table public.studyflow_users
add column if not exists email_verified boolean
not null default false;


-- --------------------------------------------------------
-- AUTH TOKENS
-- --------------------------------------------------------

create table if not exists public.studyflow_auth_tokens (

  id bigint generated by default as identity primary key,

  user_id bigint not null
    references public.studyflow_users(id)
    on delete cascade,

  token_hash text not null unique,

  token_type text not null
    check (
      token_type in (
        'reset_password',
        'verify_email'
      )
    ),

  expires_at timestamptz not null,

  used_at timestamptz,

  created_at timestamptz not null
    default now()

);


create index if not exists
studyflow_auth_tokens_user_idx

on public.studyflow_auth_tokens(user_id);


create index if not exists
studyflow_auth_tokens_expiry_idx

on public.studyflow_auth_tokens(expires_at);


alter table public.studyflow_auth_tokens
enable row level security;


grant usage
on schema public
to service_role;


grant all privileges
on table public.studyflow_auth_tokens
to service_role;


grant usage, select
on sequence public.studyflow_auth_tokens_id_seq
to service_role;


grant all privileges
on table public.studyflow_users
to service_role;

SQL


# =========================================================
# PRODUCTION SESSION STORE
# =========================================================

cat > session-config.js <<'EOF'

import session from "express-session";

import pg from "pg";

import connectPgSimple
from "connect-pg-simple";


const {
  Pool
} = pg;


export function createSessionMiddleware(){

  const secret =
    process.env.SESSION_SECRET;


  if(!secret){

    throw new Error(
      "SESSION_SECRET is missing."
    );

  }


  const databaseUrl =
    process.env.DATABASE_URL;


  let store;


  if(databaseUrl){

    const pool =
      new Pool({

        connectionString:
          databaseUrl,

        ssl:{
          rejectUnauthorized:false
        }

      });


    const PgSession =
      connectPgSimple(
        session
      );


    store =
      new PgSession({

        pool,

        tableName:
          "studyflow_sessions",

        createTableIfMissing:
          true

      });


    console.log(
      "✅ Persistent Postgres sessions enabled"
    );

  }else{

    console.warn(
      "⚠ DATABASE_URL missing — using development MemoryStore"
    );

  }


  return session({

    store,

    name:
      "studyflow.sid",

    secret,

    resave:false,

    saveUninitialized:false,

    rolling:true,

    cookie:{

      httpOnly:true,

      sameSite:"lax",

      secure:
        process.env.NODE_ENV ===
        "production",

      maxAge:
        1000 *
        60 *
        60 *
        24 *
        30

    }

  });

}

EOF


# =========================================================
# PASSWORD / EMAIL ROUTES
# =========================================================

cat > auth-extra-routes.js <<'EOF'

import express from "express";

import bcrypt from "bcryptjs";

import crypto from "crypto";

import {
  createClient
} from "@supabase/supabase-js";

import {
  Resend
} from "resend";


const router =
  express.Router();


function getSupabase(){

  const url =
    process.env.SUPABASE_URL;


  const secret =
    process.env.SUPABASE_SECRET_KEY
    ||
    process.env.SUPABASE_SERVICE_ROLE_KEY;


  if(
    !url ||
    !secret
  ){

    return null;

  }


  return createClient(
    url,
    secret,
    {

      auth:{

        persistSession:false,

        autoRefreshToken:false

      }

    }
  );

}


function normalizeEmail(value){

  return String(
    value || ""
  )
  .trim()
  .toLowerCase();

}


function createRawToken(){

  return crypto
    .randomBytes(32)
    .toString("hex");

}


function hashToken(token){

  return crypto
    .createHash("sha256")
    .update(token)
    .digest("hex");

}


function appUrl(req){

  return (
    process.env.APP_URL
    ||
    `${req.protocol}://${req.get("host")}`
  )
  .replace(/\/$/,"");

}


async function saveToken(
  supabase,
  userId,
  type,
  hours
){

  /*
    Remove older unused tokens
    of the same type.
  */

  await supabase

    .from(
      "studyflow_auth_tokens"
    )

    .delete()

    .eq(
      "user_id",
      userId
    )

    .eq(
      "token_type",
      type
    )

    .is(
      "used_at",
      null
    );


  const rawToken =
    createRawToken();


  const tokenHash =
    hashToken(
      rawToken
    );


  const expires =
    new Date(
      Date.now()
      +
      hours *
      60 *
      60 *
      1000
    );


  const {
    error
  } =
    await supabase

    .from(
      "studyflow_auth_tokens"
    )

    .insert({

      user_id:
        userId,

      token_hash:
        tokenHash,

      token_type:
        type,

      expires_at:
        expires.toISOString()

    });


  if(error){

    throw error;

  }


  return rawToken;

}


async function sendStudyFlowEmail({

  to,
  subject,
  html

}){

  const apiKey =
    process.env.RESEND_API_KEY;


  const from =
    process.env.RESEND_FROM_EMAIL;


  if(
    !apiKey ||
    !from
  ){

    return false;

  }


  const resend =
    new Resend(
      apiKey
    );


  const {
    error
  } =
    await resend.emails.send({

      from,

      to,

      subject,

      html

    });


  if(error){

    console.error(
      "Email error:",
      error
    );


    return false;

  }


  return true;

}


/* =========================================================
   FORGOT PASSWORD
========================================================= */

router.post(
  "/forgot-password",

  async (req,res) => {

    const supabase =
      getSupabase();


    /*
      Always return the same response.
      This prevents account enumeration.
    */

    const genericResponse = {

      success:true,

      message:
        "If an account exists for that email, password reset instructions have been sent."

    };


    if(!supabase){

      return res.json(
        genericResponse
      );

    }


    const email =
      normalizeEmail(
        req.body?.email
      );


    if(!email){

      return res.json(
        genericResponse
      );

    }


    try{

      const {
        data:user,
        error
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .select(
          "id,email,name"
        )

        .eq(
          "email",
          email
        )

        .maybeSingle();


      if(error){

        throw error;

      }


      if(!user){

        return res.json(
          genericResponse
        );

      }


      const token =
        await saveToken(
          supabase,
          user.id,
          "reset_password",
          1
        );


      const resetUrl =
        `${appUrl(req)}/reset-password?token=${encodeURIComponent(token)}`;


      const emailSent =
        await sendStudyFlowEmail({

          to:
            user.email,

          subject:
            "Reset your StudyFlow password",

          html:`

            <div style="
              font-family:
              Arial,
              sans-serif;
              max-width:560px;
              margin:auto;
              color:#171923;
            ">

              <h1>
                Reset your StudyFlow password
              </h1>

              <p>
                Hi ${user.name || "there"},
              </p>

              <p>
                We received a request to reset
                your StudyFlow password.
              </p>

              <p style="margin:30px 0">

                <a
                  href="${resetUrl}"
                  style="
                    background:#635bff;
                    color:#fff;
                    text-decoration:none;
                    padding:13px 20px;
                    border-radius:9px;
                    font-weight:bold;
                  "
                >
                  Reset Password
                </a>

              </p>

              <p>
                This link expires in 1 hour.
              </p>

              <p>
                If you did not request this,
                you can ignore this email.
              </p>

            </div>

          `

        });


      /*
        During LOCAL development only,
        print reset URL to Terminal.

        Never expose this URL in production.
      */

      if(
        !emailSent &&
        process.env.NODE_ENV !==
        "production"
      ){

        console.log("");
        console.log(
          "🔑 DEV RESET LINK:"
        );

        console.log(
          resetUrl
        );

        console.log("");

      }


      return res.json(
        genericResponse
      );


    }catch(error){

      console.error(
        "Forgot password:",
        error
      );


      return res.json(
        genericResponse
      );

    }

  }
);


/* =========================================================
   RESET PASSWORD
========================================================= */

router.post(
  "/reset-password",

  async (req,res) => {

    const supabase =
      getSupabase();


    if(!supabase){

      return res
        .status(503)
        .json({

          error:
            "Authentication service unavailable."

        });

    }


    const token =
      String(
        req.body?.token ||
        ""
      );


    const password =
      String(
        req.body?.password ||
        ""
      );


    if(password.length < 8){

      return res
        .status(400)
        .json({

          error:
            "Password must be at least 8 characters."

        });

    }


    if(!token){

      return res
        .status(400)
        .json({

          error:
            "Reset token is missing."

        });

    }


    try{

      const tokenHash =
        hashToken(
          token
        );


      const {
        data:record,
        error
      } =
        await supabase

        .from(
          "studyflow_auth_tokens"
        )

        .select(
          "id,user_id,expires_at,used_at"
        )

        .eq(
          "token_hash",
          tokenHash
        )

        .eq(
          "token_type",
          "reset_password"
        )

        .maybeSingle();


      if(error){

        throw error;

      }


      if(
        !record ||
        record.used_at ||
        new Date(
          record.expires_at
        ).getTime() <
        Date.now()
      ){

        return res
          .status(400)
          .json({

            error:
              "This password reset link is invalid or has expired."

          });

      }


      const passwordHash =
        await bcrypt.hash(
          password,
          12
        );


      const {
        error:updateError
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .update({

          password_hash:
            passwordHash,

          updated_at:
            new Date()
            .toISOString()

        })

        .eq(
          "id",
          record.user_id
        );


      if(updateError){

        throw updateError;

      }


      await supabase

        .from(
          "studyflow_auth_tokens"
        )

        .update({

          used_at:
            new Date()
            .toISOString()

        })

        .eq(
          "id",
          record.id
        );


      /*
        Remove other reset tokens.
      */

      await supabase

        .from(
          "studyflow_auth_tokens"
        )

        .delete()

        .eq(
          "user_id",
          record.user_id
        )

        .eq(
          "token_type",
          "reset_password"
        )

        .neq(
          "id",
          record.id
        );


      return res.json({

        success:true,

        message:
          "Password changed successfully."

      });


    }catch(error){

      console.error(
        "Reset password:",
        error
      );


      return res
        .status(500)
        .json({

          error:
            "Could not reset password."

        });

    }

  }
);


/* =========================================================
   SEND EMAIL VERIFICATION
========================================================= */

router.post(
  "/send-verification",

  async (req,res) => {

    if(
      !req.session?.userId
    ){

      return res
        .status(401)
        .json({

          error:
            "Login required."

        });

    }


    const supabase =
      getSupabase();


    if(!supabase){

      return res
        .status(503)
        .json({

          error:
            "Authentication service unavailable."

        });

    }


    try{

      const {
        data:user,
        error
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .select(
          "id,email,name,email_verified"
        )

        .eq(
          "id",
          req.session.userId
        )

        .single();


      if(error){

        throw error;

      }


      if(user.email_verified){

        return res.json({

          success:true,

          alreadyVerified:true

        });

      }


      const token =
        await saveToken(
          supabase,
          user.id,
          "verify_email",
          24
        );


      const verifyUrl =
        `${appUrl(req)}/api/verify-email?token=${encodeURIComponent(token)}`;


      const sent =
        await sendStudyFlowEmail({

          to:
            user.email,

          subject:
            "Verify your StudyFlow email",

          html:`

            <div style="
              font-family:
              Arial,
              sans-serif;
              max-width:560px;
              margin:auto;
            ">

              <h1>
                Verify your email
              </h1>

              <p>
                Welcome to StudyFlow.
              </p>

              <p>

                <a
                  href="${verifyUrl}"
                  style="
                    display:inline-block;
                    background:#635bff;
                    color:white;
                    text-decoration:none;
                    padding:13px 20px;
                    border-radius:9px;
                    font-weight:bold;
                  "
                >
                  Verify Email
                </a>

              </p>

              <p>
                This link expires in 24 hours.
              </p>

            </div>

          `

        });


      if(
        !sent &&
        process.env.NODE_ENV !==
        "production"
      ){

        console.log(
          "📧 DEV VERIFY LINK:",
          verifyUrl
        );

      }


      return res.json({

        success:true,

        emailSent:
          sent

      });


    }catch(error){

      console.error(
        "Send verification:",
        error
      );


      return res
        .status(500)
        .json({

          error:
            "Could not send verification email."

        });

    }

  }
);


/* =========================================================
   VERIFY EMAIL
========================================================= */

router.get(
  "/verify-email",

  async (req,res) => {

    const supabase =
      getSupabase();


    if(!supabase){

      return res
        .status(503)
        .send(
          "Authentication service unavailable."
        );

    }


    const token =
      String(
        req.query?.token ||
        ""
      );


    try{

      const tokenHash =
        hashToken(
          token
        );


      const {
        data:record,
        error
      } =
        await supabase

        .from(
          "studyflow_auth_tokens"
        )

        .select(
          "id,user_id,expires_at,used_at"
        )

        .eq(
          "token_hash",
          tokenHash
        )

        .eq(
          "token_type",
          "verify_email"
        )

        .maybeSingle();


      if(error){

        throw error;

      }


      if(
        !record ||
        record.used_at ||
        new Date(
          record.expires_at
        ).getTime() <
        Date.now()
      ){

        return res.redirect(
          "/app?verification=invalid"
        );

      }


      const {
        error:updateError
      } =
        await supabase

        .from(
          "studyflow_users"
        )

        .update({

          email_verified:true,

          updated_at:
            new Date()
            .toISOString()

        })

        .eq(
          "id",
          record.user_id
        );


      if(updateError){

        throw updateError;

      }


      await supabase

        .from(
          "studyflow_auth_tokens"
        )

        .update({

          used_at:
            new Date()
            .toISOString()

        })

        .eq(
          "id",
          record.id
        );


      return res.redirect(
        "/app?verification=success"
      );


    }catch(error){

      console.error(
        "Verify email:",
        error
      );


      return res.redirect(
        "/app?verification=error"
      );

    }

  }
);


export default router;

EOF


# =========================================================
# FORGOT PASSWORD PAGE
# =========================================================

cat > public/forgot-password.html <<'EOF'
<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<meta
  name="viewport"
  content="width=device-width,initial-scale=1"
>

<title>
Forgot Password — StudyFlow
</title>

<link
  rel="icon"
  href="/studyflow-icon.svg"
>

<link
  rel="stylesheet"
  href="/password-pages.css"
>

</head>


<body>

<div class="auth-page-card">

<a
  href="/"
  class="auth-logo"
>
🎓 StudyFlow
</a>


<div class="auth-icon">
🔐
</div>


<h1>
Forgot password?
</h1>


<p class="subtitle">

Enter the email associated with
your StudyFlow account.

</p>


<form id="forgotForm">

<label>
Email
</label>

<input
  id="email"
  type="email"
  placeholder="you@example.com"
  required
>


<button type="submit">
Send Reset Link
</button>

</form>


<div
  id="message"
  class="message hidden"
></div>


<a
  class="back-link"
  href="/app"
>
← Back to StudyFlow
</a>

</div>


<script>

const form =
  document.getElementById(
    "forgotForm"
  );


form.addEventListener(
  "submit",

  async event => {

    event.preventDefault();


    const button =
      form.querySelector(
        "button"
      );


    button.disabled =
      true;


    button.textContent =
      "Sending...";


    const message =
      document.getElementById(
        "message"
      );


    try{

      const response =
        await fetch(
          "/api/forgot-password",
          {

            method:"POST",

            headers:{
              "Content-Type":
                "application/json"
            },

            body:
              JSON.stringify({

                email:
                  document
                  .getElementById(
                    "email"
                  )
                  .value

              })

          }
        );


      const data =
        await response.json();


      message.textContent =
        data.message ||
        "Check your email for password reset instructions.";


      message.className =
        "message success";


      form.reset();


    }catch(error){

      message.textContent =
        "Something went wrong. Please try again.";


      message.className =
        "message error";

    }


    button.disabled =
      false;


    button.textContent =
      "Send Reset Link";

  }
);

</script>

</body>

</html>
EOF


# =========================================================
# RESET PAGE
# =========================================================

cat > public/reset-password.html <<'EOF'
<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<meta
  name="viewport"
  content="width=device-width,initial-scale=1"
>

<title>
Reset Password — StudyFlow
</title>

<link
  rel="icon"
  href="/studyflow-icon.svg"
>

<link
  rel="stylesheet"
  href="/password-pages.css"
>

</head>


<body>

<div class="auth-page-card">

<a
  href="/"
  class="auth-logo"
>
🎓 StudyFlow
</a>


<div class="auth-icon">
🔑
</div>


<h1>
Create a new password
</h1>


<p class="subtitle">
Choose a strong new password
for your StudyFlow account.
</p>


<form id="resetForm">

<label>
New password
</label>

<input
  id="password"
  type="password"
  minlength="8"
  placeholder="At least 8 characters"
  required
>


<label>
Confirm password
</label>

<input
  id="confirmPassword"
  type="password"
  minlength="8"
  placeholder="Repeat password"
  required
>


<button type="submit">
Reset Password
</button>

</form>


<div
  id="message"
  class="message hidden"
></div>


<a
  class="back-link"
  href="/app"
>
← Back to StudyFlow
</a>

</div>


<script>

const params =
  new URLSearchParams(
    location.search
  );


const token =
  params.get(
    "token"
  );


const form =
  document.getElementById(
    "resetForm"
  );


const message =
  document.getElementById(
    "message"
  );


if(!token){

  message.textContent =
    "This reset link is invalid.";


  message.className =
    "message error";


  form.style.display =
    "none";

}


form.addEventListener(
  "submit",

  async event => {

    event.preventDefault();


    const password =
      document.getElementById(
        "password"
      ).value;


    const confirm =
      document.getElementById(
        "confirmPassword"
      ).value;


    if(
      password !==
      confirm
    ){

      message.textContent =
        "Passwords do not match.";


      message.className =
        "message error";


      return;

    }


    const button =
      form.querySelector(
        "button"
      );


    button.disabled =
      true;


    button.textContent =
      "Updating...";


    try{

      const response =
        await fetch(
          "/api/reset-password",
          {

            method:"POST",

            headers:{
              "Content-Type":
                "application/json"
            },

            body:
              JSON.stringify({

                token,

                password

              })

          }
        );


      const data =
        await response.json();


      if(!response.ok){

        throw new Error(
          data.error ||
          "Reset failed."
        );

      }


      message.textContent =
        "✅ Password changed. You can now log in.";


      message.className =
        "message success";


      form.style.display =
        "none";


      setTimeout(
        () => {

          location.href =
            "/app";

        },
        1800
      );


    }catch(error){

      message.textContent =
        error.message;


      message.className =
        "message error";

    }


    button.disabled =
      false;


    button.textContent =
      "Reset Password";

  }
);

</script>

</body>

</html>
EOF


# =========================================================
# PASSWORD PAGE CSS
# =========================================================

cat > public/password-pages.css <<'EOF'

*{
box-sizing:border-box;
}

body{
margin:0;
min-height:100vh;
display:grid;
place-items:center;
padding:25px;
background:
radial-gradient(
circle at top left,
#635bff26,
transparent 35%
),
radial-gradient(
circle at bottom right,
#a855f726,
transparent 35%
),
#f6f7fb;
font-family:
Inter,
-apple-system,
BlinkMacSystemFont,
"Segoe UI",
sans-serif;
color:#181a22;
}

.auth-page-card{
width:min(430px,100%);
background:#fff;
border:1px solid #e6e7ed;
border-radius:22px;
padding:34px;
box-shadow:
0 30px 80px
rgba(35,31,90,.13);
}

.auth-logo{
display:inline-block;
text-decoration:none;
font-weight:850;
color:#181a22;
margin-bottom:30px;
}

.auth-icon{
font-size:44px;
}

h1{
font-size:29px;
letter-spacing:-1px;
margin:10px 0 8px;
}

.subtitle{
font-size:14px;
color:#777d88;
line-height:1.55;
margin-bottom:25px;
}

label{
display:block;
font-size:12px;
font-weight:800;
margin:13px 0 6px;
}

input{
width:100%;
border:1px solid #dfe1e7;
border-radius:10px;
padding:12px;
font-size:14px;
outline:none;
}

input:focus{
border-color:#635bff;
box-shadow:
0 0 0 3px
#635bff15;
}

button{
width:100%;
margin-top:19px;
border:0;
border-radius:10px;
padding:13px;
background:#635bff;
color:#fff;
font-weight:800;
cursor:pointer;
}

button:disabled{
opacity:.6;
}

.message{
margin-top:17px;
padding:12px;
border-radius:9px;
font-size:13px;
line-height:1.5;
}

.message.success{
background:#ecfdf5;
color:#15803d;
}

.message.error{
background:#fff1f2;
color:#be123c;
}

.hidden{
display:none;
}

.back-link{
display:block;
margin-top:22px;
text-align:center;
font-size:13px;
font-weight:700;
color:#635bff;
text-decoration:none;
}

EOF


# =========================================================
# PATCH SERVER
# =========================================================

python3 <<'PY'

from pathlib import Path


p = Path(
    "server.js"
)

s = p.read_text()


# ---------------------------------------------------------
# IMPORTS
# ---------------------------------------------------------

imports = [
    'import { createSessionMiddleware } from "./session-config.js";',
    'import authExtraRouter from "./auth-extra-routes.js";'
]


lines =
    s.splitlines()


for import_line in imports:

    if import_line not in s:

        last_import =
            max(
                [
                    i
                    for i,line
                    in enumerate(lines)
                    if line.startswith("import ")
                ],
                default=-1
            )


        lines.insert(
            last_import + 1,
            import_line
        )


        s =
            "\n".join(lines)


        lines =
            s.splitlines()


# ---------------------------------------------------------
# REPLACE EXPRESS SESSION MIDDLEWARE
# ---------------------------------------------------------

if "app.use(createSessionMiddleware());" not in s:

    start =
        s.find(
            "app.use(session("
        )


    if start != -1:

        depth =
            0


        i =
            start


        found_open =
            False


        while i < len(s):

            char =
                s[i]


            if char == "(":

                depth += 1

                found_open =
                    True


            elif char == ")":

                depth -= 1


                if (
                    found_open
                    and depth == 0
                ):

                    end =
                        i + 1


                    while (
                        end < len(s)
                        and s[end]
                        in " \t\r\n;"
                    ):

                        end += 1


                    s = (
                        s[:start]
                        +
                        "app.use(createSessionMiddleware());\n\n"
                        +
                        s[end:]
                    )


                    break


            i += 1

    else:

        marker =
            "app.use(express.json"


        pos =
            s.find(marker)


        if pos != -1:

            line_end =
                s.find(
                    "\n",
                    pos
                )


            s = (
                s[:line_end + 1]
                +
                "\napp.use(createSessionMiddleware());\n"
                +
                s[line_end + 1:]
            )


# ---------------------------------------------------------
# EXTRA AUTH ROUTER
# ---------------------------------------------------------

mount_line =
    'app.use("/api", authExtraRouter);'


if mount_line not in s:

    marker =
        'app.use("/api/cloud", cloudRouter);'


    if marker in s:

        s =
            s.replace(
                marker,
                mount_line
                +
                "\n\n"
                +
                marker,
                1
            )

    else:

        marker =
            'app.use("/api", supabaseAuthRouter);'


        if marker in s:

            s =
                s.replace(
                    marker,
                    marker
                    +
                    "\n"
                    +
                    mount_line,
                    1
                )


# ---------------------------------------------------------
# PASSWORD PAGES
# ---------------------------------------------------------

page_routes = r'''

app.get("/forgot-password", (req, res) => {

  res.sendFile(
    "forgot-password.html",
    {
      root:"public"
    }
  );

});


app.get("/reset-password", (req, res) => {

  res.sendFile(
    "reset-password.html",
    {
      root:"public"
    }
  );

});

'''


if 'app.get("/forgot-password"' not in s:

    static_marker =
        'app.use(express.static("public"));'


    if static_marker in s:

        s =
            s.replace(
                static_marker,
                page_routes
                +
                "\n"
                +
                static_marker,
                1
            )


p.write_text(s)


print(
    "✅ server.js production auth installed"
)

PY


# =========================================================
# ADD FORGOT PASSWORD LINK TO APP
# =========================================================

python3 <<'PY'

from pathlib import Path


p = Path(
    "public/index.html"
)

html =
    p.read_text()


forgot = '''

<div class="studyflow-forgot-password-link">

  <a href="/forgot-password">
    Forgot password?
  </a>

</div>

'''


if "studyflow-forgot-password-link" not in html:

    candidates = [
        "Create account",
        "Create Account",
        "Register"
    ]


    inserted =
        False


    for candidate in candidates:

        pos =
            html.find(candidate)


        if pos != -1:

            closing =
                html.find(
                    "</button>",
                    pos
                )


            if closing != -1:

                closing += len(
                    "</button>"
                )


                html = (
                    html[:closing]
                    +
                    forgot
                    +
                    html[closing:]
                )


                inserted =
                    True

                break


    if not inserted:

        html = html.replace(
            "</body>",
            forgot +
            "\n</body>"
        )


p.write_text(html)

PY


cat >> public/style.css <<'EOF'


/* PART 8 AUTH */

.studyflow-forgot-password-link{
text-align:center;
margin-top:11px;
}

.studyflow-forgot-password-link a{
font-size:12px;
font-weight:700;
color:var(--primary);
text-decoration:none;
}

.studyflow-forgot-password-link a:hover{
text-decoration:underline;
}

EOF


# =========================================================
# ENV PLACEHOLDERS
# =========================================================

touch .env


if ! grep -q "^DATABASE_URL=" .env
then

  echo "" >> .env
  echo "DATABASE_URL=" >> .env

fi


if ! grep -q "^APP_URL=" .env
then

  echo "APP_URL=http://localhost:3000" >> .env

fi


if ! grep -q "^RESEND_API_KEY=" .env
then

  echo "RESEND_API_KEY=" >> .env

fi


if ! grep -q "^RESEND_FROM_EMAIL=" .env
then

  echo "RESEND_FROM_EMAIL=" >> .env

fi


# =========================================================
# CHECKS
# =========================================================

echo ""
echo "🧪 Checking code..."
echo ""

node --check session-config.js
echo "✅ session-config.js"

node --check auth-extra-routes.js
echo "✅ auth-extra-routes.js"

node --check server.js
echo "✅ server.js"

node --check public/app.js
echo "✅ app.js"


# =========================================================
# COPY SQL
# =========================================================

if command -v pbcopy >/dev/null 2>&1
then

  pbcopy < supabase-production-auth.sql

  echo ""
  echo "📋 Supabase PART 8 SQL copied to clipboard"

fi


echo ""
echo "============================================"
echo "🎉 PART 8 PRODUCTION AUTH CODE INSTALLED"
echo "============================================"
echo ""
echo "Added:"
echo "• Persistent Postgres login sessions"
echo "• 30-day login session"
echo "• Secure httpOnly cookies"
echo "• Forgot Password"
echo "• Reset Password"
echo "• Hashed one-time reset tokens"
echo "• 1-hour reset expiry"
echo "• Email verification backend"
echo "• Verification tokens"
echo "• Optional Resend email delivery"
echo ""
echo "NEXT:"
echo ""
echo "1. Supabase → SQL Editor → New Query"
echo "2. Command + V"
echo "3. Run"
echo ""
echo "Then add DATABASE_URL to .env."
echo ""
echo "🚫 Do not paste database passwords or API keys into chat."
echo ""

