
-- ========================================================
-- StudyFlow Production Authentication
-- ========================================================

alter table public.studyflow_users
add column if not exists email_verified boolean
not null default false;


-- --------------------------------------------------------
-- AUTH TOKENS
-- --------------------------------------------------------

create table if not exists public.studyflow_auth_tokens (

  id bigint generated by default as identity primary key,

  user_id bigint not null
    references public.studyflow_users(id)
    on delete cascade,

  token_hash text not null unique,

  token_type text not null
    check (
      token_type in (
        'reset_password',
        'verify_email'
      )
    ),

  expires_at timestamptz not null,

  used_at timestamptz,

  created_at timestamptz not null
    default now()

);


create index if not exists
studyflow_auth_tokens_user_idx

on public.studyflow_auth_tokens(user_id);


create index if not exists
studyflow_auth_tokens_expiry_idx

on public.studyflow_auth_tokens(expires_at);


alter table public.studyflow_auth_tokens
enable row level security;


grant usage
on schema public
to service_role;


grant all privileges
on table public.studyflow_auth_tokens
to service_role;


grant usage, select
on sequence public.studyflow_auth_tokens_id_seq
to service_role;


grant all privileges
on table public.studyflow_users
to service_role;

