
create table if not exists public.studyflow_users (

  id bigint generated by default as identity primary key,

  email text not null unique,

  password_hash text not null,

  name text not null default '',

  university text not null default '',

  major text not null default '',

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now()

);


create unique index if not exists
studyflow_users_email_lower_idx

on public.studyflow_users (
  lower(email)
);


alter table public.studyflow_users
enable row level security;

